In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
OHcrime_2017 = "Resources/OhioCrime2017_NoNan.csv"
OHcrime_2016 = "Resources/OhioCrime2016_NoNan.csv"
OHcrime_2015 = "Resources/OhioCrime2015_NoNan.csv"
OHcrime_2014 = "Resources/OhioCrime2014_NoNan.csv"
OHcrime_2013 = "Resources/OhioCrime2013_NoNan.csv"
OHcrime_2012 = "Resources/OhioCrime2012_NoNan.csv"

OHcrime_2017_df = pd.read_csv(OHcrime_2017)
OHcrime_2016_df = pd.read_csv(OHcrime_2016)
OHcrime_2015_df = pd.read_csv(OHcrime_2015)
OHcrime_2014_df = pd.read_csv(OHcrime_2014)
OHcrime_2013_df = pd.read_csv(OHcrime_2013)
OHcrime_2012_df = pd.read_csv(OHcrime_2012)

In [3]:
combined_crime_df = pd.merge(OHcrime_2017_df, OHcrime_2016_df, how="left", on="City")

#combined_crime_df.reset_index(drop=True)
#combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
combined_crime_df

,Unnamed: 0_x,County_x,City,POPULATION_x,VIOLENT CRIME_x,MURDER_x,RAPE_x,ROBBERY_x,AGGRAVATED ASSAULT_x,Crime_Percent2017,Unnamed: 0_y,County_y,POPULATION_y,VIOLENT CRIME_y,MURDER_y,RAPE_y,ROBBERY_y,AGGRAVATED ASSAULT_y
0,7,Allen County,Lima,37220,275,5,52,81,137,738.850081,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,25.081515,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,76.394194,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,0.000000,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,54.466231,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0
5,12,Allen County,Fort Shawnee,12096,14,1,4,3,6,115.740741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16,Ashland County,Ashland,20485,25,0,7,4,14,122.040518,18.0,Ashland County,20278.0,24.0,2.0,14.0,1.0,7.0
7,17,Ashland County,Loudonville,2581,3,1,1,1,0,116.234018,19.0,Ashland County,2561.0,14.0,0.0,7.0,0.0,7.0
8,19,Ashtabula County,Geneva,1199,7,0,3,1,3,583.819850,21.0,Ashtabula County,1207.0,7.0,1.0,2.0,0.0,4.0
9,20,Ashtabula County,Roaming Shores,1466,0,0,0,0,0,0.000000,22.0,Ashtabula County,1471.0,0.0,0.0,0.0,0.0,0.0
10,21,Ashtabula County,Ashtabula,49924,42,0,8,4,30,84.127874,23.0,Ashtabula County,49784.0,54.0,1.0,10.0,14.0,29.0
11,22,Athens County,Athens,25526,34,0,4,6,24,133.197524,24.0,Athens County,25203.0,27.0,0.0,6.0,8.0,13.0
12,23,Athens County,Glouster,1793,3,0,1,0,2,167.317345,25.0,Athens County,1798.0,3.0,0.0,2.0,0.0,1.0
13,24,Athens County,Nelsonville,5284,13,0,2,4,7,246.025738,26.0,Athens County,5159.0,11.0,0.0,1.0,7.0,3.0
14,25,Athens County,Albany,899,0,0,0,0,0,0.000000,27.0,Athens County,918.0,0.0,0.0,0.0,0.0,0.0
15,27,Athens County,Coolville,492,0,0,0,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,29,Auglaize County,Saint Marys,8215,3,0,0,1,2,36.518564,30.0,Auglaize County,8256.0,5.0,0.0,0.0,2.0,3.0
17,30,Auglaize County,Wapakoneta,9809,14,0,6,3,5,142.726068,31.0,Auglaize County,9815.0,10.0,0.0,3.0,0.0,7.0
18,31,Auglaize County,Minster,2866,0,0,0,0,0,0.000000,32.0,Auglaize County,2853.0,0.0,0.0,0.0,0.0,0.0
19,32,Auglaize County,New Bremen,2966,0,0,0,0,0,0.000000,33.0,Auglaize County,2961.0,0.0,0.0,0.0,0.0,0.0
20,33,Auglaize County,New Knoxville,864,0,0,0,0,0,0.000000,34.0,Auglaize County,865.0,0.0,0.0,0.0,0.0,0.0
21,35,Belmont County,Barnesville,4096,0,0,0,0,0,0.000000,36.0,Belmont County,4112.0,1.0,0.0,0.0,0.0,1.0
22,38,Belmont County,Martins Ferry,6731,13,0,6,0,7,193.136235,39.0,Belmont County,6761.0,12.0,0.0,2.0,0.0,10.0
23,39,Belmont County,Powhatan Point,1562,0,0,0,0,0,0.000000,40.0,Belmont County,1569.0,1.0,0.0,0.0,0.0,1.0
24,41,Belmont County,Saint Clairsville,5096,1,0,0,0,1,19.623234,42.0,Belmont County,5090.0,4.0,0.0,0.0,0.0,4.0
25,42,Belmont County,Flushing,858,0,0,0,0,0,0.000000,43.0,Belmont County,860.0,0.0,0.0,0.0,0.0,0.0
26,44,Belmont County,Belmont,29108,34,2,10,2,20,116.806376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46,Brown County,Georgetown,4356,10,0,6,3,1,229.568411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,47,Brown County,Ripley,1707,2,0,1,0,1,117.164616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,48,Brown County,Mount Orab,3525,4,1,2,0,1,113.475177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,621,Tuscarawas County,Dennison,2625,2,0,0,0,2,76.190476,614.0,Tuscarawas County,2638.0,2.0,0.0,0.0,0.0,2.0
328,633,Franklin County,Dublin,2510,1,0,1,0,0,39.840637,196.0,Franklin County,38892.0,20.0,0.0,8.0,5.0,7.0
329,634,Union County,Marysville,23622,17,1,4,3,9,71.966811,628.0,Union County,22952.0,7.0,0.0,2.0,1.0,4.0
330,636,Allen County,Delphos,3052,3,0,3,0,0,98.296199,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
331,637,Van Wert County,Van Wert,10713,22,1,7,3,11,205.357976,631.0,Van Wert County,10794.0,29.0,0.0,10.0,1.0,18.0
332,641,Butler County,Middletown,2759,14,0,2,5,7,507.430228,55.0,Butler County,46067.0,242.0,5.0,41.0,67.0,129.0
333,643,Clermont County,Loveland,823,0,0,0,0,0,0.000000,90.0,Clermont County,2036.0,0.0,0.0,0.0,0.0,0.0
334,644,Warren County,Franklin,11779,31,1,6,13,11,263.180236,638.0,Warren County,11782.0,23.0,1.0,4.0,10.0,8.0
335,646,Warren County,Lebanon,20741,4,0,0,1,3,19.285473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,647,Warren County,Mason,33406,12,0,5,3,4,35.921691,640.0,Warren County,33026.0,6.0,0.0,3.0,2.0,1.0
337,650,Warren County,Maineville,1070,0,0,0,0,0,0.000000,643.0,Warren County,992.0,0.0,0.0,0.0,0.0,0.0
338,651,Warren County,Springboro,17359,10,0,5,0,5,57.607005,644.0,Warren County,17119.0,11.0,0.0,6.0,1.0,4.0
339,654,Washington County,Belpre,6466,2,0,0,0,2,30.931024,647.0,Washington County,6484.0,11.0,0.0,3.0,2.0,6.0
340,655,Washington County,Marietta,13582,23,0,11,2,10,169.341776,648.0,Washington County,13867.0,8.0,0.0,2.0,4.0,2.0
341,659,Wayne County,Orrville,8527,15,0,6,0,9,175.911810,652.0,Wayne County,8514.0,16.0,3.0,4.0,1.0,8.0
342,660,Wayne County,Rittman,6496,9,0,3,2,4,138.546798,653.0,Wayne County,6484.0,4.0,0.0,1.0,1.0,2.0
343,661,Wayne County,Wooster,27172,102,0,30,24,48,375.386427,654.0,Wayne County,26883.0,73.0,0.0,24.0,14.0,35.0
344,662,Wayne County,Apple Creek,1188,2,0,0,0,2,168.350168,655.0,Wayne County,1186.0,0.0,0.0,0.0,0.0,0.0
345,663,Wayne County,Creston,2097,1,0,0,0,1,47.687172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,664,Wayne County,Marshallville,761,1,0,1,0,0,131.406045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,665,Wayne County,Smithville,1277,1,0,1,0,0,78.308536,657.0,Wayne County,1273.0,3.0,0.0,1.0,0.0,2.0
348,667,Williams County,Montpelier,3976,27,0,5,1,21,679.074447,659.0,Williams County,3980.0,14.0,1.0,5.0,3.0,5.0
349,668,Williams County,Pioneer,1412,3,0,2,0,1,212.464589,660.0,Williams County,1406.0,2.0,0.0,1.0,0.0,1.0
350,670,Wood County,Bowling Green,31779,41,0,20,6,15,129.016017,663.0,Wood County,31404.0,42.0,0.0,19.0,8.0,15.0
351,671,Wood County,North Baltimore,3546,10,0,2,0,8,282.007896,664.0,Wood County,3568.0,9.0,0.0,2.0,2.0,5.0
352,672,Wood County,Perrysburg,21732,7,0,3,4,0,32.210565,665.0,Wood County,21548.0,8.0,0.0,3.0,3.0,2.0
353,674,Wood County,Bradner,1024,1,0,0,0,1,97.656250,667.0,Wood County,1026.0,0.0,0.0,0.0,0.0,0.0
354,675,Wood County,Northwood,5423,19,0,2,4,13,350.359580,669.0,Wood County,5376.0,6.0,0.0,2.0,3.0,1.0
355,676,Wood County,Pemberville,1425,0,0,0,0,0,0.000000,670.0,Wood County,1433.0,1.0,0.0,1.0,0.0,0.0
356,677,Wood County,Wayne,927,0,0,0,0,0,0.000000,671.0,Wood County,900.0,0.0,0.0,0.0,0.0,0.0

In [4]:
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_x":"2017 Population",
                                                              "VIOLENT CRIME_x":"2017 Violent Crime",
                                                              "MURDER_x":"2017 Murder", "RAPE_x": "2017 Rape",
                                                              "ROBBERY_x": "2017 Robbery", "AGGRAVATED ASSAULT_x": 
                                                              "2017 Aggravated Assault"})

# Rename our _y columns to 2016
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_y":"2016 Population",
                                                              "VIOLENT CRIME_y":"2016 Violent Crime",
                                                              "MURDER_y":"2016 Murder", "RAPE_y": "2016 Rape",
                                                              "ROBBERY_y": "2016 Robbery", "AGGRAVATED ASSAULT_y": 
                                                              "2016 Aggravated Assault"})
combined_crime_df.head()

,Unnamed: 0_x,County_x,City,2017 Population,2017 Violent Crime,2017 Murder,2017 Rape,2017 Robbery,2017 Aggravated Assault,Crime_Percent2017,Unnamed: 0_y,County_y,2016 Population,2016 Violent Crime,2016 Murder,2016 Rape,2016 Robbery,2016 Aggravated Assault
0,7,Allen County,Lima,37220,275,5,52,81,137,738.850081,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,25.081515,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,76.394194,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,0.000000,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,54.466231,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# Merge our newly combined dataframe with the 2015 dataframe

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2015_df, how="left", on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2015 Population",
                                                        "VIOLENT CRIME":"2015 Violent Crime",
                                                        "MURDER":"2015 Murder", "RAPE": "2015 Rape",
                                                        "ROBBERY": "2015 Robbery", "AGGRAVATED ASSAULT": 
                                                        "2015 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2014_df, how="left",on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2014 Population",
                                                      "VIOLENT CRIME":"2014 Violent Crime",
                                                      "MURDER":"2014 Murder", "RAPE": "2014 Rape",
                                                      "ROBBERY": "2014 Robbery", "AGGRAVATED ASSAULT": 
                                                    "2014 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2013_df, how="left", on="City")
combined_crime_df
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2013 Population",
                                                       "VIOLENT CRIME":"2013 Violent Crime",
                                                       "MURDER":"2013 Murder", "RAPE": "2013 Rape",
                                                       "ROBBERY": "2013 Robbery", "AGGRAVATED ASSAULT": 
                                                     "2013 Aggravated Assault"})
#combined_crime_df = pd.merge(combined_crime_df, OHcrime_2012_df, on="City")
#combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2012 Population",
#                                                        "VIOLENT CRIME":"2012 Violent Crime",
#                                                        "MURDER":"2012 Murder", "RAPE": "2012 Rape",
#                                                        "ROBBERY": "2012 Robbery", "AGGRAVATED ASSAULT": 
#                                                      "2012 Aggravated Assault"})

#combined_crimeGrouped = combined_crime_df.groupby("City")
#combined_crime_df= combined_crimeGrouped.sum()
#combined_crime_df=combined_crime_df.reset_index()
combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
#combined_crime_df
combined_crime_df=combined_crime_df.sort_values("2017 Population", ascending=False)
combined_crime_df

,Unnamed: 0_x,County_x,City,2017 Population,2017 Violent Crime,2017 Murder,2017 Rape,2017 Robbery,2017 Aggravated Assault,Crime_Percent2017,...,2014 Robbery,2014 Aggravated Assault,Unnamed: 0,County,2013 Population,2013 Violent Crime,2013 Murder,2013 Rape,2013 Robbery,2013 Aggravated Assault
114,197,Franklin County,Columbus,853424,4379,139,899,1919,1422,513.109545,...,2112.0,1656.0,230.0,Franklin County,816364.0,4446.0,78.0,692.0,2463.0,1213.0
65,117,Cuyahoga County,Cleveland,385351,5999,107,497,2697,2698,1556.762536,...,2992.0,1655.0,143.0,Cuyahoga County,389181.0,5782.0,58.0,436.0,3496.0,1792.0
149,257,Hamilton County,Cincinnati,299116,2833,70,292,1196,1275,947.124193,...,1358.0,1053.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,381,Lucas County,Toledo,277116,2829,35,180,780,1834,1020.872126,...,944.0,1869.0,450.0,Lucas County,283035.0,2902.0,28.0,129.0,962.0,1783.0
308,583,Summit County,Akron,197412,1377,42,209,395,731,697.525986,...,436.0,728.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,456,Dayton,Dayton,140171,1232,30,122,393,687,878.926454,...,537.0,529.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,144,Cuyahoga County,Parma,79340,141,0,39,37,65,177.716158,...,30.0,17.0,172.0,Cuyahoga County,80303.0,87.0,1.0,23.0,31.0,32.0
111,194,Butler County,Fairfield,75853,38,0,15,6,17,50.096898,...,19.0,65.0,66.0,Butler County,42677.0,120.0,1.0,12.0,37.0,70.0
293,566,Stark County,Canton,71031,836,16,97,188,535,1176.950909,...,229.0,403.0,668.0,Stark County,72598.0,673.0,11.0,72.0,357.0,233.0
208,401,Mahoning County,Youngstown,63878,447,23,32,151,241,699.771439,...,132.0,244.0,469.0,Mahoning County,64927.0,528.0,14.0,27.0,170.0,317.0
193,375,Lorain County,Lorain,63672,373,2,30,87,254,585.814801,...,91.0,115.0,442.0,Lorain County,63582.0,303.0,6.0,30.0,161.0,106.0
31,53,Butler County,Hamilton,62094,312,3,75,111,123,502.464006,...,39.0,40.0,67.0,Butler County,62268.0,378.0,6.0,52.0,189.0,131.0
35,59,Butler County,West Chester,61386,64,0,21,15,28,104.258300,...,22.0,19.0,73.0,Butler County,59435.0,43.0,1.0,11.0,15.0,16.0
38,71,Clark County,Springfield,58843,370,9,25,177,159,628.791870,...,223.0,162.0,91.0,Clark County,60012.0,427.0,6.0,46.0,208.0,167.0
238,459,Dayton,Kettering,54681,70,0,23,26,21,128.015216,...,18.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,371,Lorain County,Elyria,53586,191,3,39,64,85,356.436383,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,136,Cuyahoga County,Lakewood,50151,74,2,6,40,26,147.554386,...,32.0,26.0,164.0,Cuyahoga County,51167.0,48.0,1.0,10.0,24.0,13.0
10,21,Ashtabula County,Ashtabula,49924,42,0,8,4,30,84.127874,...,9.0,22.0,31.0,Ashtabula County,51042.0,40.0,1.0,4.0,7.0,28.0
310,585,Summit County,Cuyahoga Falls,49145,49,2,18,8,21,99.704955,...,9.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,129,Cuyahoga County,Euclid,47270,303,4,26,118,155,640.998519,...,4.0,8.0,158.0,Cuyahoga County,48095.0,93.0,NaN,13.0,23.0,57.0
177,343,Lake County,Mentor,46663,72,0,11,17,44,154.297838,...,3.0,NaN,403.0,Lake County,46979.0,43.0,NaN,20.0,11.0,12.0
143,247,Greene County,Beavercreek,46572,38,0,13,9,16,81.594091,...,11.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,543,Richland County,Mansfield,46507,248,7,45,75,121,533.253059,...,88.0,81.0,637.0,Richland County,46832.0,180.0,NaN,44.0,82.0,54.0
32,54,Butler County,Middletown,46069,235,5,39,82,109,510.104409,...,77.0,177.0,68.0,Butler County,45971.0,285.0,NaN,37.0,71.0,177.0
89,152,Cuyahoga County,Strongsville,44758,18,2,1,9,6,40.216274,...,8.0,33.0,180.0,Cuyahoga County,44583.0,27.0,NaN,3.0,4.0,20.0
71,127,Cuyahoga County,Cleveland Heights,44525,131,2,16,79,34,294.216732,...,57.0,37.0,156.0,Cuyahoga County,46309.0,144.0,1.0,5.0,94.0,44.0
30,52,Butler County,Fairfield,42627,90,1,11,12,66,211.133788,...,19.0,65.0,66.0,Butler County,42677.0,120.0,1.0,12.0,37.0,70.0
163,294,Hancock County,Findlay,41474,128,3,25,24,76,308.627092,...,17.0,41.0,342.0,Hancock County,41660.0,76.0,1.0,13.0,18.0,44.0
306,579,Mahoning County,North Jackson,40624,58,1,14,24,19,142.772745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,205,Franklin County,Grove City,40421,47,4,14,24,5,116.276193,...,18.0,4.0,237.0,Franklin County,37208.0,40.0,1.0,5.0,29.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,581,Stark County,Magnolia,714,1,0,1,0,0,140.056022,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,180,Erie County,Berlin Heights,713,0,0,0,0,0,0.000000,...,NaN,NaN,212.0,Erie County,702.0,NaN,NaN,NaN,NaN,NaN
209,402,Columbiana County,Columbiana,650,0,0,0,0,0,0.000000,...,NaN,2.0,120.0,Columbiana County,5654.0,4.0,NaN,NaN,NaN,4.0
319,596,Summit County,Peninsula,563,0,0,0,0,0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,188,Fairfield County,Carroll,520,0,0,0,0,0,0.000000,...,NaN,NaN,221.0,Fairfield County,524.0,NaN,NaN,NaN,NaN,NaN
170,311,Hocking County,Laurelville,507,1,0,0,1,0,197.238659,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,27,Athens County,Coolville,492,0,0,0,0,0,0.000000,...,NaN,NaN,40.0,Athens County,488.0,NaN,NaN,NaN,NaN,NaN
145,252,Dayton,Kettering,471,0,0,0,0,0,0.000000,...,18.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,256,Guernsey County,Senecaville,448,0,0,0,0,0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,192,Fairfield County,Sugar Grove,433,0,0,0,0,0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,75,Clark County,South Vienna,375,0,0,0,0,0,0.000000,...,NaN,NaN,95.0,Clark County,381.0,NaN,NaN,NaN,NaN,NaN
172,316,Erie County,Milan,356,0,0,0,0,0,0.000000,...,NaN,NaN,213.0,Erie County,990.0,1.0,NaN,1.0,NaN,NaN
276,530,Summit County,Tallmadge,287,0,0,0,0,0,0.000000,...,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,66,Stark County,Magnolia,258,0,0,0,0,0,0.000000,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,293,Allen County,Bluffton,170,0,0,0,0,0,0.000000,...,1.0,2.0,12.0,Allen County,3824.0,1.0,NaN,NaN,NaN,1.0
183,359,Franklin County,New Albany,168,0,0,0,0,0,0.000000,...,NaN,3.0,249.0,Franklin County,8743.0,2.0,NaN,NaN,NaN,2.0
199,382,Fulton County,Swanton,145,0,0,0,0,0,0.000000,...,NaN,NaN,267.0,Fulton County,3582.0,3.0,NaN,1.0,1.0,1.0
260,496,Ottawa County,Put in Bay,135,0,0,0,0,0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,434,Wayne County,Rittman,114,0,0,0,0,0,0.000000,...,2.0,NaN,776.0,Wayne County,6390.0,7.0,NaN,1.0,3.0,3.0
225,435,Wayne County,Creston,91,0,0,0,0,0,0.000000,...,2.0,2.0,779.0,Wayne County,2072.0,1.0,NaN,NaN,1.0,NaN
116,199,Fairfield County,Pickerington,76,0,0,0,0,0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,313,Ashland County,Loudonville,61,0,0,0,0,0,0.000000,...,NaN,NaN,23.0,Ashland County,2557.0,NaN,NaN,NaN,NaN,NaN
115,198,Fairfield County,Lithopolis,42,0,0,0,0,0,0.000000,...,NaN,NaN,222.0,Fairfield County,1170.0,NaN,NaN,NaN,NaN,NaN
218,421,Stark County,Alliance,35,0,0,0,0,0,0.000000,...,19.0,46.0,670.0,Stark County,22104.0,83.0,1.0,14.0,12.0,56.0
150,258,Clermont County,Milford,29,0,0,0,0,0,0.000000,...,6.0,5.0,101.0,Clermont County,6642.0,6.0,NaN,NaN,1.0,5.0
321,605,Mahoning County,Youngstown,11,0,0,0,0,0,0.000000,...,132.0,244.0,469.0,Mahoning County,64927.0,528.0,14.0,27.0,170.0,317.0
210,403,Columbiana County,Salem,4,0,0,0,0,0,0.000000,...,4.0,6.0,124.0,Columbiana County,12111.0,6.0,1.0,NaN,1.0,4.0
62,109,Stark County,Minerva,2,0,0,0,0,0,0.000000,...,NaN,1.0,676.0,Stark County,1937.0,NaN,NaN,NaN,NaN,NaN
55,96,Highland County,Lynchburg,2,0,0,0,0,0,0.000000,...,NaN,3.0,362.0,Highland County,1470.0,1.0,NaN,NaN,NaN,1.0
144,251,Dayton,Centerville,2,0,0,0,0,0,0.000000,...,5.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
Final_CrimeRateData = combined_crime_df[['City','2017 Population', '2017 Violent Crime',
         '2016 Population', '2016 Violent Crime', '2015 Population', '2015 Violent Crime', '2014 Population', '2014 Violent Crime']]

# violent_crimetableGrouped = violent_crimetable.groupby("City")
# Final_CrimeRateData= violent_crimetableGrouped.sum()
Final_CrimeRateData.head(20)
#new_df = pd.DataFrame(violent_crimetableGrouped["2017 Population", "2017 Violent Crime", "2016 Population", "2016 Violent
                      #Crime"].sum()
#DataFrame without City duplicates:

,City,2017 Population,2017 Violent Crime,2016 Population,2016 Violent Crime,2015 Population,2015 Violent Crime,2014 Population,2014 Violent Crime
114,Columbus,853424,4379,862515.0,4500.0,847745.0,4758.0,830811.0,4640.0
65,Cleveland,385351,5999,386227.0,6299.0,387921.0,4506.0,388655.0,5205.0
149,Cincinnati,299116,2833,298880.0,2720.0,298478.0,2788.0,297671.0,2719.0
198,Toledo,277116,2829,278366.0,3319.0,279552.0,3156.0,281150.0,3068.0
308,Akron,197412,1377,197257.0,1216.0,197587.0,1225.0,197891.0,1366.0
235,Dayton,140171,1232,140260.0,1402.0,140683.0,1339.0,143217.0,1237.0
82,Parma,79340,141,79576.0,108.0,79655.0,79.0,80168.0,68.0
111,Fairfield,75853,38,42810.0,110.0,42824.0,91.0,42654.0,98.0
293,Canton,71031,836,71652.0,677.0,72111.0,814.0,72391.0,730.0
208,Youngstown,63878,447,64170.0,415.0,64597.0,478.0,64658.0,427.0
193,Lorain,63672,373,63561.0,127.0,63700.0,171.0,63619.0,244.0
31,Hamilton,62094,312,62423.0,320.0,62526.0,355.0,62240.0,105.0
35,West Chester,61386,64,61080.0,43.0,60365.0,76.0,59629.0,56.0
38,Springfield,58843,370,59503.0,411.0,59804.0,355.0,58891.0,442.0
238,Kettering,54681,70,54915.0,73.0,55106.0,71.0,55311.0,53.0
189,Elyria,53586,191,53633.0,161.0,53843.0,8.0,NaN,NaN
77,Lakewood,50151,74,50349.0,63.0,50653.0,19.0,50923.0,66.0
10,Ashtabula,49924,42,49784.0,54.0,50154.0,59.0,50631.0,37.0
310,Cuyahoga Falls,49145,49,49064.0,67.0,49124.0,50.0,49196.0,49.0
73,Euclid,47270,303,47416.0,275.0,47664.0,221.0,47969.0,12.0

In [7]:

# Final_CrimeRateData["Crime Rate 2017"] = ((Final_CrimeRateData["2017 Violent Crime"])/(Final_CrimeRateData["2017 Population"]))*100
# Final_CrimeRateData["Crime Rate 2016"] = ((Final_CrimeRateData["2016 Violent Crime"])/(Final_CrimeRateData["2016 Population"]))*100
# Final_CrimeRateData["Crime Rate 2015"] = ((Final_CrimeRateData["2015 Violent Crime"])/(Final_CrimeRateData["2015 Population"]))*100
# Final_CrimeRateData["Crime Rate 2014"] = ((Final_CrimeRateData["2014 Violent Crime"])/(Final_CrimeRateData["2014 Population"]))*100

# Final_CrimeRateData.head()
# # #violent_crimetableUpdate = violent_crimetable.sort_values("2017 Population", ascending=False)
# Final_CrimeRateData.to_csv("Resources/CrimeRate.csv")
# Final_CrimeRateData.head()