In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
OHcrime_2017 = "Resources/OhioCrime2017_NoNan.csv"
OHcrime_2016 = "Resources/OhioCrime2016_NoNan.csv"
OHcrime_2015 = "Resources/OhioCrime2015_NoNan.csv"
OHcrime_2014 = "Resources/OhioCrime2014_NoNan.csv"
OHcrime_2013 = "Resources/OhioCrime2013_NoNan.csv"
OHcrime_2012 = "Resources/OhioCrime2012_NoNan.csv"

OHcrime_2017_df = pd.read_csv(OHcrime_2017)
OHcrime_2016_df = pd.read_csv(OHcrime_2016)
OHcrime_2015_df = pd.read_csv(OHcrime_2015)
OHcrime_2014_df = pd.read_csv(OHcrime_2014)
OHcrime_2013_df = pd.read_csv(OHcrime_2013)
OHcrime_2012_df = pd.read_csv(OHcrime_2012)

In [3]:
combined_crime_df = pd.merge(OHcrime_2017_df, OHcrime_2016_df, how = 'left', on="City")

#combined_crime_df.reset_index(drop=True)
#combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
combined_crime_df

,Unnamed: 0_x,County_x,City,POPULATION_x,VIOLENT CRIME_x,MURDER_x,RAPE_x,ROBBERY_x,AGGRAVATED ASSAULT_x,Unnamed: 0_y,County_y,POPULATION_y,VIOLENT CRIME_y,MURDER_y,RAPE_y,ROBBERY_y,AGGRAVATED ASSAULT_y
0,7,Allen County,Lima,37220,275,5,52,81,137,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0
5,12,Allen County,Fort Shawnee,12096,14,1,4,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16,Ashland County,Ashland,20485,25,0,7,4,14,18.0,Ashland County,20278.0,24.0,2.0,14.0,1.0,7.0
7,17,Ashland County,Loudonville,2581,3,1,1,1,0,19.0,Ashland County,2561.0,14.0,0.0,7.0,0.0,7.0
8,19,Ashtabula County,Geneva,1199,7,0,3,1,3,21.0,Ashtabula County,1207.0,7.0,1.0,2.0,0.0,4.0
9,20,Ashtabula County,Roaming Shores,1466,0,0,0,0,0,22.0,Ashtabula County,1471.0,0.0,0.0,0.0,0.0,0.0
10,21,Ashtabula County,Ashtabula,49924,42,0,8,4,30,23.0,Ashtabula County,49784.0,54.0,1.0,10.0,14.0,29.0
11,22,Athens County,Athens,25526,34,0,4,6,24,24.0,Athens County,25203.0,27.0,0.0,6.0,8.0,13.0
12,23,Athens County,Glouster,1793,3,0,1,0,2,25.0,Athens County,1798.0,3.0,0.0,2.0,0.0,1.0
13,24,Athens County,Nelsonville,5284,13,0,2,4,7,26.0,Athens County,5159.0,11.0,0.0,1.0,7.0,3.0
14,25,Athens County,Albany,899,0,0,0,0,0,27.0,Athens County,918.0,0.0,0.0,0.0,0.0,0.0
15,27,Athens County,Coolville,492,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,29,Auglaize County,Saint Marys,8215,3,0,0,1,2,30.0,Auglaize County,8256.0,5.0,0.0,0.0,2.0,3.0
17,30,Auglaize County,Wapakoneta,9809,14,0,6,3,5,31.0,Auglaize County,9815.0,10.0,0.0,3.0,0.0,7.0
18,31,Auglaize County,Minster,2866,0,0,0,0,0,32.0,Auglaize County,2853.0,0.0,0.0,0.0,0.0,0.0
19,32,Auglaize County,New Bremen,2966,0,0,0,0,0,33.0,Auglaize County,2961.0,0.0,0.0,0.0,0.0,0.0
20,33,Auglaize County,New Knoxville,864,0,0,0,0,0,34.0,Auglaize County,865.0,0.0,0.0,0.0,0.0,0.0
21,35,Belmont County,Barnesville,4096,0,0,0,0,0,36.0,Belmont County,4112.0,1.0,0.0,0.0,0.0,1.0
22,38,Belmont County,Martins Ferry,6731,13,0,6,0,7,39.0,Belmont County,6761.0,12.0,0.0,2.0,0.0,10.0
23,39,Belmont County,Powhatan Point,1562,0,0,0,0,0,40.0,Belmont County,1569.0,1.0,0.0,0.0,0.0,1.0
24,41,Belmont County,Saint Clairsville,5096,1,0,0,0,1,42.0,Belmont County,5090.0,4.0,0.0,0.0,0.0,4.0
25,42,Belmont County,Flushing,858,0,0,0,0,0,43.0,Belmont County,860.0,0.0,0.0,0.0,0.0,0.0
26,44,Belmont County,Belmont,29108,34,2,10,2,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46,Brown County,Georgetown,4356,10,0,6,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,47,Brown County,Ripley,1707,2,0,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,48,Brown County,Mount Orab,3525,4,1,2,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,621,Tuscarawas County,Dennison,2625,2,0,0,0,2,614.0,Tuscarawas County,2638.0,2.0,0.0,0.0,0.0,2.0
326,633,Franklin County,Dublin,2510,1,0,1,0,0,196.0,Franklin County,38892.0,20.0,0.0,8.0,5.0,7.0
327,634,Union County,Marysville,23622,17,1,4,3,9,628.0,Union County,22952.0,7.0,0.0,2.0,1.0,4.0
328,636,Allen County,Delphos,3052,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
329,637,Van Wert County,Van Wert,10713,22,1,7,3,11,631.0,Van Wert County,10794.0,29.0,0.0,10.0,1.0,18.0
330,641,Butler County,Middletown,2759,14,0,2,5,7,55.0,Butler County,46067.0,242.0,5.0,41.0,67.0,129.0
331,643,Clermont County,Loveland,823,0,0,0,0,0,90.0,Clermont County,2036.0,0.0,0.0,0.0,0.0,0.0
332,644,Warren County,Franklin,11779,31,1,6,13,11,638.0,Warren County,11782.0,23.0,1.0,4.0,10.0,8.0
333,646,Warren County,Lebanon,20741,4,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,647,Warren County,Mason,33406,12,0,5,3,4,640.0,Warren County,33026.0,6.0,0.0,3.0,2.0,1.0
335,650,Warren County,Maineville,1070,0,0,0,0,0,643.0,Warren County,992.0,0.0,0.0,0.0,0.0,0.0
336,651,Warren County,Springboro,17359,10,0,5,0,5,644.0,Warren County,17119.0,11.0,0.0,6.0,1.0,4.0
337,654,Washington County,Belpre,6466,2,0,0,0,2,647.0,Washington County,6484.0,11.0,0.0,3.0,2.0,6.0
338,655,Washington County,Marietta,13582,23,0,11,2,10,648.0,Washington County,13867.0,8.0,0.0,2.0,4.0,2.0
339,659,Wayne County,Orrville,8527,15,0,6,0,9,652.0,Wayne County,8514.0,16.0,3.0,4.0,1.0,8.0
340,660,Wayne County,Rittman,6496,9,0,3,2,4,653.0,Wayne County,6484.0,4.0,0.0,1.0,1.0,2.0
341,661,Wayne County,Wooster,27172,102,0,30,24,48,654.0,Wayne County,26883.0,73.0,0.0,24.0,14.0,35.0
342,662,Wayne County,Apple Creek,1188,2,0,0,0,2,655.0,Wayne County,1186.0,0.0,0.0,0.0,0.0,0.0
343,663,Wayne County,Creston,2097,1,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,664,Wayne County,Marshallville,761,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,665,Wayne County,Smithville,1277,1,0,1,0,0,657.0,Wayne County,1273.0,3.0,0.0,1.0,0.0,2.0
346,667,Williams County,Montpelier,3976,27,0,5,1,21,659.0,Williams County,3980.0,14.0,1.0,5.0,3.0,5.0
347,668,Williams County,Pioneer,1412,3,0,2,0,1,660.0,Williams County,1406.0,2.0,0.0,1.0,0.0,1.0
348,670,Wood County,Bowling Green,31779,41,0,20,6,15,663.0,Wood County,31404.0,42.0,0.0,19.0,8.0,15.0
349,671,Wood County,North Baltimore,3546,10,0,2,0,8,664.0,Wood County,3568.0,9.0,0.0,2.0,2.0,5.0
350,672,Wood County,Perrysburg,21732,7,0,3,4,0,665.0,Wood County,21548.0,8.0,0.0,3.0,3.0,2.0
351,674,Wood County,Bradner,1024,1,0,0,0,1,667.0,Wood County,1026.0,0.0,0.0,0.0,0.0,0.0
352,675,Wood County,Northwood,5423,19,0,2,4,13,669.0,Wood County,5376.0,6.0,0.0,2.0,3.0,1.0
353,676,Wood County,Pemberville,1425,0,0,0,0,0,670.0,Wood County,1433.0,1.0,0.0,1.0,0.0,0.0
354,677,Wood County,Wayne,927,0,0,0,0,0,671.0,Wood County,900.0,0.0,0.0,0.0,0.0,0.0

In [4]:
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_x":"2017 Population",
                                                              "VIOLENT CRIME_x":"2017 Violent Crime",
                                                              "MURDER_x":"2017 Murder", "RAPE_x": "2017 Rape",
                                                              "ROBBERY_x": "2017 Robbery", "AGGRAVATED ASSAULT_x": 
                                                              "2017 Aggravated Assault"})

# Rename our _y columns to 2016
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_y":"2016 Population",
                                                              "VIOLENT CRIME_y":"2016 Violent Crime",
                                                              "MURDER_y":"2016 Murder", "RAPE_y": "2016 Rape",
                                                              "ROBBERY_y": "2016 Robbery", "AGGRAVATED ASSAULT_y": 
                                                              "2016 Aggravated Assault"})
combined_crime_df.head()

,Unnamed: 0_x,County_x,City,2017 Population,2017 Violent Crime,2017 Murder,2017 Rape,2017 Robbery,2017 Aggravated Assault,Unnamed: 0_y,County_y,2016 Population,2016 Violent Crime,2016 Murder,2016 Rape,2016 Robbery,2016 Aggravated Assault
0,7,Allen County,Lima,37220,275,5,52,81,137,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# Merge our newly combined dataframe with the 2015 dataframe

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2015_df, how = 'left', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2015 Population",
                                                        "VIOLENT CRIME":"2015 Violent Crime",
                                                        "MURDER":"2015 Murder", "RAPE": "2015 Rape",
                                                        "ROBBERY": "2015 Robbery", "AGGRAVATED ASSAULT": 
                                                        "2015 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2014_df, how = 'left', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2014 Population",
                                                      "VIOLENT CRIME":"2014 Violent Crime",
                                                      "MURDER":"2014 Murder", "RAPE": "2014 Rape",
                                                      "ROBBERY": "2014 Robbery", "AGGRAVATED ASSAULT": 
                                                    "2014 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2013_df, how = 'left', on="City")
combined_crime_df
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2013 Population",
                                                       "VIOLENT CRIME":"2013 Violent Crime",
                                                       "MURDER":"2013 Murder", "RAPE": "2013 Rape",
                                                       "ROBBERY": "2013 Robbery", "AGGRAVATED ASSAULT": 
                                                     "2013 Aggravated Assault"})
combined_crime_df = pd.merge(combined_crime_df, OHcrime_2012_df, how = 'left', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2012 Population",
                                                       "VIOLENT CRIME":"2012 Violent Crime",
                                                       "MURDER":"2012 Murder", "RAPE": "2012 Rape",
                                                       "ROBBERY": "2012 Robbery", "AGGRAVATED ASSAULT": 
                                                     "2012 Aggravated Assault"})

#combined_crimeGrouped = combined_crime_df.groupby("City")
#combined_crime_df= combined_crimeGrouped.sum()
#combined_crime_df=combined_crime_df.reset_index()
combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
#combined_crime_df
combined_crime_df=combined_crime_df.sort_values("2017 Population", ascending=False)
combined_crime_df

,Unnamed: 0_x,County_x,City,2017 Population,2017 Violent Crime,2017 Murder,2017 Rape,2017 Robbery,2017 Aggravated Assault,Unnamed: 0_y,...,2013 Robbery,2013 Aggravated Assault,Unnamed: 0_y,County_y,2012 Population,2012 Violent Crime,2012 Murder,FORCIBLE RAPE,2012 Robbery,AGG ASSAULT
112,197,Franklin County,Columbus,872205,4478,142,919,1963,1454,191.0,...,2463.0,1213.0,229.0,Franklin County,816364.0,4446.0,78.0,692.0,2463.0,1213.0
65,117,Cuyahoga County,Cleveland,385351,5999,107,497,2697,2698,115.0,...,3496.0,1792.0,137.0,Cuyahoga County,393781.0,5469.0,85.0,373.0,3257.0,1754.0
147,257,Hamilton County,Cincinnati,299116,2833,70,292,1196,1275,249.0,...,NaN,NaN,297.0,Hamilton County,296204.0,2903.0,47.0,199.0,1726.0,931.0
196,381,Lucas County,Toledo,277116,2829,35,180,780,1834,373.0,...,962.0,1783.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,583,Summit County,Akron,197412,1377,42,209,395,731,576.0,...,NaN,NaN,681.0,Summit County,198390.0,1777.0,25.0,173.0,580.0,999.0
233,456,Dayton,Dayton,140171,1232,30,122,393,687,449.0,...,NaN,NaN,531.0,Montgomery County,142139.0,1401.0,26.0,116.0,638.0,621.0
82,144,Cuyahoga County,Parma,79340,141,0,39,37,65,141.0,...,31.0,32.0,168.0,Cuyahoga County,80963.0,58.0,NaN,4.0,15.0,39.0
109,194,Butler County,Fairfield,75853,38,0,15,6,17,53.0,...,37.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,566,Stark County,Canton,71031,836,16,97,188,535,559.0,...,357.0,233.0,660.0,Stark County,72914.0,729.0,10.0,64.0,414.0,241.0
206,401,Mahoning County,Youngstown,63878,447,23,32,151,241,393.0,...,170.0,317.0,468.0,Mahoning County,66556.0,685.0,22.0,39.0,244.0,380.0
191,375,Lorain County,Lorain,63672,373,2,30,87,254,367.0,...,161.0,106.0,442.0,Lorain County,64148.0,326.0,4.0,35.0,136.0,151.0
31,53,Butler County,Hamilton,62094,312,3,75,111,123,54.0,...,189.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,59,Butler County,West Chester,61386,64,0,21,15,28,60.0,...,15.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,71,Clark County,Springfield,58843,370,9,25,177,159,72.0,...,208.0,167.0,89.0,Clark County,60329.0,373.0,5.0,38.0,178.0,152.0
236,459,Dayton,Kettering,54681,70,0,23,26,21,452.0,...,NaN,NaN,534.0,Montgomery County,55952.0,50.0,NaN,22.0,20.0,8.0
187,371,Lorain County,Elyria,53586,191,3,39,64,85,363.0,...,NaN,NaN,439.0,Lorain County,54578.0,NaN,NaN,NaN,NaN,NaN
77,136,Cuyahoga County,Lakewood,50151,74,2,6,40,26,134.0,...,24.0,13.0,159.0,Cuyahoga County,51721.0,65.0,3.0,3.0,34.0,25.0
10,21,Ashtabula County,Ashtabula,49924,42,0,8,4,30,23.0,...,7.0,28.0,29.0,Ashtabula County,51589.0,65.0,2.0,10.0,10.0,43.0
308,585,Summit County,Cuyahoga Falls,49145,49,2,18,8,21,578.0,...,NaN,NaN,683.0,Summit County,49470.0,65.0,NaN,17.0,13.0,35.0
73,129,Cuyahoga County,Euclid,47270,303,4,26,118,155,128.0,...,23.0,57.0,152.0,Cuyahoga County,48538.0,92.0,NaN,12.0,34.0,46.0
175,343,Lake County,Mentor,46663,72,0,11,17,44,336.0,...,11.0,12.0,402.0,Lake County,47123.0,53.0,NaN,15.0,27.0,11.0
141,247,Greene County,Beavercreek,46572,38,0,13,9,16,239.0,...,NaN,NaN,286.0,Greene County,45563.0,25.0,NaN,6.0,13.0,6.0
281,543,Richland County,Mansfield,46507,248,7,45,75,121,535.0,...,82.0,54.0,627.0,Richland County,47480.0,178.0,1.0,27.0,93.0,57.0
32,54,Butler County,Middletown,46069,235,5,39,82,109,55.0,...,71.0,177.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,152,Cuyahoga County,Strongsville,44758,18,2,1,9,6,148.0,...,4.0,20.0,176.0,Cuyahoga County,44397.0,13.0,NaN,6.0,5.0,2.0
71,127,Cuyahoga County,Cleveland Heights,44525,131,2,16,79,34,126.0,...,94.0,44.0,150.0,Cuyahoga County,45761.0,168.0,NaN,10.0,110.0,48.0
30,52,Butler County,Fairfield,42627,90,1,11,12,66,53.0,...,37.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,294,Hancock County,Findlay,41474,128,3,25,24,76,283.0,...,18.0,44.0,337.0,Hancock County,41348.0,77.0,NaN,19.0,20.0,38.0
304,579,Mahoning County,North Jackson,40624,58,1,14,24,19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,205,Franklin County,Grove City,40421,47,4,14,24,5,199.0,...,29.0,5.0,237.0,Franklin County,36050.0,38.0,1.0,12.0,21.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,581,Stark County,Magnolia,714,1,0,1,0,0,574.0,...,NaN,NaN,678.0,Stark County,711.0,NaN,NaN,NaN,NaN,NaN
99,180,Erie County,Berlin Heights,713,0,0,0,0,0,NaN,...,NaN,NaN,210.0,Erie County,711.0,NaN,NaN,NaN,NaN,NaN
207,402,Columbiana County,Columbiana,650,0,0,0,0,0,98.0,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,596,Summit County,Peninsula,563,0,0,0,0,0,589.0,...,NaN,NaN,690.0,Summit County,562.0,NaN,NaN,NaN,NaN,NaN
103,188,Fairfield County,Carroll,520,0,0,0,0,0,183.0,...,NaN,NaN,218.0,Fairfield County,526.0,NaN,NaN,NaN,NaN,NaN
168,311,Hocking County,Laurelville,507,1,0,0,1,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,27,Athens County,Coolville,492,0,0,0,0,0,NaN,...,NaN,NaN,37.0,Athens County,495.0,NaN,NaN,NaN,NaN,NaN
143,252,Dayton,Kettering,471,0,0,0,0,0,452.0,...,NaN,NaN,534.0,Montgomery County,55952.0,50.0,NaN,22.0,20.0,8.0
146,256,Guernsey County,Senecaville,448,0,0,0,0,0,248.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,192,Fairfield County,Sugar Grove,433,0,0,0,0,0,NaN,...,NaN,NaN,222.0,Fairfield County,428.0,NaN,NaN,NaN,NaN,NaN
41,75,Clark County,South Vienna,375,0,0,0,0,0,75.0,...,NaN,NaN,93.0,Clark County,381.0,NaN,NaN,NaN,NaN,NaN
170,316,Erie County,Milan,356,0,0,0,0,0,175.0,...,NaN,NaN,211.0,Erie County,1001.0,NaN,NaN,NaN,NaN,NaN
274,530,Summit County,Tallmadge,287,0,0,0,0,0,585.0,...,NaN,NaN,687.0,Summit County,17193.0,18.0,NaN,13.0,NaN,5.0
37,66,Stark County,Magnolia,258,0,0,0,0,0,574.0,...,NaN,NaN,678.0,Stark County,711.0,NaN,NaN,NaN,NaN,NaN
160,293,Allen County,Bluffton,170,0,0,0,0,0,10.0,...,NaN,1.0,11.0,Allen County,3945.0,5.0,NaN,1.0,1.0,3.0
181,359,Franklin County,New Albany,168,0,0,0,0,0,210.0,...,NaN,2.0,248.0,Franklin County,7808.0,2.0,NaN,NaN,NaN,2.0
197,382,Fulton County,Swanton,145,0,0,0,0,0,220.0,...,1.0,1.0,263.0,Fulton County,3565.0,NaN,NaN,NaN,NaN,NaN
258,496,Ottawa County,Put in Bay,135,0,0,0,0,0,490.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,434,Wayne County,Rittman,114,0,0,0,0,0,653.0,...,3.0,3.0,767.0,Wayne County,6380.0,4.0,NaN,NaN,NaN,4.0
223,435,Wayne County,Creston,91,0,0,0,0,0,NaN,...,1.0,NaN,769.0,Wayne County,2073.0,NaN,NaN,NaN,NaN,NaN
114,199,Fairfield County,Pickerington,76,0,0,0,0,0,186.0,...,NaN,NaN,221.0,Fairfield County,18320.0,NaN,NaN,NaN,NaN,NaN
169,313,Ashland County,Loudonville,61,0,0,0,0,0,19.0,...,NaN,NaN,23.0,Ashland County,2587.0,3.0,NaN,NaN,1.0,2.0
113,198,Fairfield County,Lithopolis,42,0,0,0,0,0,184.0,...,NaN,NaN,219.0,Fairfield County,1080.0,NaN,NaN,NaN,NaN,NaN
216,421,Stark County,Alliance,35,0,0,0,0,0,561.0,...,12.0,56.0,662.0,Stark County,22253.0,96.0,2.0,17.0,31.0,46.0
148,258,Clermont County,Milford,29,0,0,0,0,0,79.0,...,1.0,5.0,99.0,Clermont County,6739.0,16.0,NaN,NaN,3.0,13.0
319,605,Mahoning County,Youngstown,11,0,0,0,0,0,393.0,...,170.0,317.0,468.0,Mahoning County,66556.0,685.0,22.0,39.0,244.0,380.0
208,403,Columbiana County,Salem,4,0,0,0,0,0,101.0,...,1.0,4.0,121.0,Columbiana County,12265.0,4.0,NaN,1.0,1.0,2.0
55,96,Highland County,Lynchburg,2,0,0,0,0,0,299.0,...,NaN,1.0,358.0,Highland County,29165.0,44.0,NaN,3.0,NaN,41.0
142,251,Dayton,Centerville,2,0,0,0,0,0,450.0,...,NaN,NaN,532.0,Montgomery County,24105.0,19.0,NaN,2.0,5.0,12.0
62,109,Stark County,Minerva,2,0,0,0,0,0,567.0,...,NaN,NaN,668.0,Stark County,1939.0,2.0,NaN,1.0,NaN,1.0

In [6]:
Final_CrimeRateData = combined_crime_df[['City','2017 Population', '2017 Violent Crime',
         '2016 Population', '2016 Violent Crime', '2015 Population', '2015 Violent Crime', '2014 Population', '2014 Violent Crime']]

# violent_crimetableGrouped = violent_crimetable.groupby("City")
# Final_CrimeRateData= violent_crimetableGrouped.sum()
Final_CrimeRateData.head(20)
#new_df = pd.DataFrame(violent_crimetableGrouped["2017 Population", "2017 Violent Crime", "2016 Population", "2016 Violent
                      #Crime"].sum()
#DataFrame without City duplicates:

,City,2017 Population,2017 Violent Crime,2016 Population,2016 Violent Crime,2015 Population,2015 Violent Crime,2014 Population,2014 Violent Crime
112,Columbus,872205,4478,862515.0,4500.0,847745.0,4758.0,830811.0,4640.0
65,Cleveland,385351,5999,386227.0,6299.0,387921.0,4506.0,388655.0,5205.0
147,Cincinnati,299116,2833,298880.0,2720.0,298478.0,2788.0,297671.0,2719.0
196,Toledo,277116,2829,278366.0,3319.0,279552.0,3156.0,281150.0,3068.0
306,Akron,197412,1377,197257.0,1216.0,197587.0,1225.0,197891.0,1366.0
233,Dayton,140171,1232,140260.0,1402.0,140683.0,1339.0,143217.0,1237.0
82,Parma,79340,141,79576.0,108.0,79655.0,79.0,80168.0,68.0
109,Fairfield,75853,38,42810.0,110.0,42824.0,91.0,42654.0,98.0
291,Canton,71031,836,71652.0,677.0,72111.0,814.0,72391.0,730.0
206,Youngstown,63878,447,64170.0,415.0,64597.0,478.0,64658.0,427.0
191,Lorain,63672,373,63561.0,127.0,63700.0,171.0,63619.0,244.0
31,Hamilton,62094,312,62423.0,320.0,62526.0,355.0,62240.0,105.0
35,West Chester,61386,64,61080.0,43.0,60365.0,76.0,59629.0,56.0
38,Springfield,58843,370,59503.0,411.0,59804.0,355.0,58891.0,442.0
236,Kettering,54681,70,54915.0,73.0,55106.0,71.0,55311.0,53.0
187,Elyria,53586,191,53633.0,161.0,53843.0,8.0,NaN,NaN
77,Lakewood,50151,74,50349.0,63.0,50653.0,19.0,50923.0,66.0
10,Ashtabula,49924,42,49784.0,54.0,50154.0,59.0,50631.0,37.0
308,Cuyahoga Falls,49145,49,49064.0,67.0,49124.0,50.0,49196.0,49.0
73,Euclid,47270,303,47416.0,275.0,47664.0,221.0,47969.0,12.0

In [7]:

Final_CrimeRateData["Crime Rate 2017"] = ((Final_CrimeRateData["2017 Violent Crime"])/(Final_CrimeRateData["2017 Population"]))*100
Final_CrimeRateData["Crime Rate 2016"] = ((Final_CrimeRateData["2016 Violent Crime"])/(Final_CrimeRateData["2016 Population"]))*100
Final_CrimeRateData["Crime Rate 2015"] = ((Final_CrimeRateData["2015 Violent Crime"])/(Final_CrimeRateData["2015 Population"]))*100
Final_CrimeRateData["Crime Rate 2014"] = ((Final_CrimeRateData["2014 Violent Crime"])/(Final_CrimeRateData["2014 Population"]))*100

Final_CrimeRateData.head()
# #violent_crimetableUpdate = violent_crimetable.sort_values("2017 Population", ascending=False)
Final_CrimeRateData.to_csv("Resources/CrimeRate.csv")
Final_CrimeRateData.head()

C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,City,2017 Population,2017 Violent Crime,2016 Population,2016 Violent Crime,2015 Population,2015 Violent Crime,2014 Population,2014 Violent Crime,Crime Rate 2017,Crime Rate 2016,Crime Rate 2015,Crime Rate 2014
112,Columbus,872205,4478,862515.0,4500.0,847745.0,4758.0,830811.0,4640.0,0.513411,0.521730,0.561254,0.558490
65,Cleveland,385351,5999,386227.0,6299.0,387921.0,4506.0,388655.0,5205.0,1.556763,1.630906,1.161577,1.339234
147,Cincinnati,299116,2833,298880.0,2720.0,298478.0,2788.0,297671.0,2719.0,0.947124,0.910064,0.934072,0.913425
196,Toledo,277116,2829,278366.0,3319.0,279552.0,3156.0,281150.0,3068.0,1.020872,1.192315,1.128949,1.091232
306,Akron,197412,1377,197257.0,1216.0,197587.0,1225.0,197891.0,1366.0,0.697526,0.616455,0.619980,0.690279