In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
OHcrime_2017 = "Resources/OhioCrime2017_NoNan.csv"
OHcrime_2016 = "Resources/OhioCrime2016_NoNan.csv"
OHcrime_2015 = "Resources/OhioCrime2015_NoNan.csv"
OHcrime_2014 = "Resources/OhioCrime2014_NoNan.csv"
OHcrime_2013 = "Resources/OhioCrime2013_NoNan.csv"
OHcrime_2012 = "Resources/OhioCrime2012_NoNan.csv"

OHcrime_2017_df = pd.read_csv(OHcrime_2017)
OHcrime_2016_df = pd.read_csv(OHcrime_2016)
OHcrime_2015_df = pd.read_csv(OHcrime_2015)
OHcrime_2014_df = pd.read_csv(OHcrime_2014)
OHcrime_2013_df = pd.read_csv(OHcrime_2013)
OHcrime_2012_df = pd.read_csv(OHcrime_2012)

In [3]:
combined_crime_df = pd.merge(OHcrime_2017_df, OHcrime_2016_df, how = 'left', on="City")

#combined_crime_df.reset_index(drop=True)
#combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
combined_crime_df

,Unnamed: 0_x,County_x,City,POPULATION_x,VIOLENT CRIME_x,MURDER_x,RAPE_x,ROBBERY_x,AGGRAVATED ASSAULT_x,Unnamed: 0_y,County_y,POPULATION_y,VIOLENT CRIME_y,MURDER_y,RAPE_y,ROBBERY_y,AGGRAVATED ASSAULT_y
0,7,Allen County,Lima,37220,275,5,52,81,137,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0
5,12,Allen County,Fort Shawnee,12096,14,1,4,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16,Ashland County,Ashland,20485,25,0,7,4,14,18.0,Ashland County,20278.0,24.0,2.0,14.0,1.0,7.0
7,17,Ashland County,Loudonville,2581,3,1,1,1,0,19.0,Ashland County,2561.0,14.0,0.0,7.0,0.0,7.0
8,19,Ashtabula County,Geneva,1199,7,0,3,1,3,21.0,Ashtabula County,1207.0,7.0,1.0,2.0,0.0,4.0
9,20,Ashtabula County,Roaming Shores,1466,0,0,0,0,0,22.0,Ashtabula County,1471.0,0.0,0.0,0.0,0.0,0.0
10,21,Ashtabula County,Ashtabula,49924,42,0,8,4,30,23.0,Ashtabula County,49784.0,54.0,1.0,10.0,14.0,29.0
11,22,Athens County,Athens,25526,34,0,4,6,24,24.0,Athens County,25203.0,27.0,0.0,6.0,8.0,13.0
12,23,Athens County,Glouster,1793,3,0,1,0,2,25.0,Athens County,1798.0,3.0,0.0,2.0,0.0,1.0
13,24,Athens County,Nelsonville,5284,13,0,2,4,7,26.0,Athens County,5159.0,11.0,0.0,1.0,7.0,3.0
14,25,Athens County,Albany,899,0,0,0,0,0,27.0,Athens County,918.0,0.0,0.0,0.0,0.0,0.0
15,27,Athens County,Coolville,492,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,29,Auglaize County,Saint Marys,8215,3,0,0,1,2,30.0,Auglaize County,8256.0,5.0,0.0,0.0,2.0,3.0
17,30,Auglaize County,Wapakoneta,9809,14,0,6,3,5,31.0,Auglaize County,9815.0,10.0,0.0,3.0,0.0,7.0
18,31,Auglaize County,Minster,2866,0,0,0,0,0,32.0,Auglaize County,2853.0,0.0,0.0,0.0,0.0,0.0
19,32,Auglaize County,New Bremen,2966,0,0,0,0,0,33.0,Auglaize County,2961.0,0.0,0.0,0.0,0.0,0.0
20,33,Auglaize County,New Knoxville,864,0,0,0,0,0,34.0,Auglaize County,865.0,0.0,0.0,0.0,0.0,0.0
21,35,Belmont County,Barnesville,4096,0,0,0,0,0,36.0,Belmont County,4112.0,1.0,0.0,0.0,0.0,1.0
22,38,Belmont County,Martins Ferry,6731,13,0,6,0,7,39.0,Belmont County,6761.0,12.0,0.0,2.0,0.0,10.0
23,39,Belmont County,Powhatan Point,1562,0,0,0,0,0,40.0,Belmont County,1569.0,1.0,0.0,0.0,0.0,1.0
24,41,Belmont County,Saint Clairsville,5096,1,0,0,0,1,42.0,Belmont County,5090.0,4.0,0.0,0.0,0.0,4.0
25,42,Belmont County,Flushing,858,0,0,0,0,0,43.0,Belmont County,860.0,0.0,0.0,0.0,0.0,0.0
26,44,Belmont County,Belmont,29108,34,2,10,2,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46,Brown County,Georgetown,4356,10,0,6,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,47,Brown County,Ripley,1707,2,0,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,48,Brown County,Mount Orab,3525,4,1,2,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,621,Tuscarawas County,Dennison,2625,2,0,0,0,2,614.0,Tuscarawas County,2638.0,2.0,0.0,0.0,0.0,2.0
328,633,Franklin County,Dublin,2510,1,0,1,0,0,196.0,Franklin County,38892.0,20.0,0.0,8.0,5.0,7.0
329,634,Union County,Marysville,23622,17,1,4,3,9,628.0,Union County,22952.0,7.0,0.0,2.0,1.0,4.0
330,636,Allen County,Delphos,3052,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
331,637,Van Wert County,Van Wert,10713,22,1,7,3,11,631.0,Van Wert County,10794.0,29.0,0.0,10.0,1.0,18.0
332,641,Butler County,Middletown,2759,14,0,2,5,7,55.0,Butler County,46067.0,242.0,5.0,41.0,67.0,129.0
333,643,Clermont County,Loveland,823,0,0,0,0,0,90.0,Clermont County,2036.0,0.0,0.0,0.0,0.0,0.0
334,644,Warren County,Franklin,11779,31,1,6,13,11,638.0,Warren County,11782.0,23.0,1.0,4.0,10.0,8.0
335,646,Warren County,Lebanon,20741,4,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,647,Warren County,Mason,33406,12,0,5,3,4,640.0,Warren County,33026.0,6.0,0.0,3.0,2.0,1.0
337,650,Warren County,Maineville,1070,0,0,0,0,0,643.0,Warren County,992.0,0.0,0.0,0.0,0.0,0.0
338,651,Warren County,Springboro,17359,10,0,5,0,5,644.0,Warren County,17119.0,11.0,0.0,6.0,1.0,4.0
339,654,Washington County,Belpre,6466,2,0,0,0,2,647.0,Washington County,6484.0,11.0,0.0,3.0,2.0,6.0
340,655,Washington County,Marietta,13582,23,0,11,2,10,648.0,Washington County,13867.0,8.0,0.0,2.0,4.0,2.0
341,659,Wayne County,Orrville,8527,15,0,6,0,9,652.0,Wayne County,8514.0,16.0,3.0,4.0,1.0,8.0
342,660,Wayne County,Rittman,6496,9,0,3,2,4,653.0,Wayne County,6484.0,4.0,0.0,1.0,1.0,2.0
343,661,Wayne County,Wooster,27172,102,0,30,24,48,654.0,Wayne County,26883.0,73.0,0.0,24.0,14.0,35.0
344,662,Wayne County,Apple Creek,1188,2,0,0,0,2,655.0,Wayne County,1186.0,0.0,0.0,0.0,0.0,0.0
345,663,Wayne County,Creston,2097,1,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,664,Wayne County,Marshallville,761,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,665,Wayne County,Smithville,1277,1,0,1,0,0,657.0,Wayne County,1273.0,3.0,0.0,1.0,0.0,2.0
348,667,Williams County,Montpelier,3976,27,0,5,1,21,659.0,Williams County,3980.0,14.0,1.0,5.0,3.0,5.0
349,668,Williams County,Pioneer,1412,3,0,2,0,1,660.0,Williams County,1406.0,2.0,0.0,1.0,0.0,1.0
350,670,Wood County,Bowling Green,31779,41,0,20,6,15,663.0,Wood County,31404.0,42.0,0.0,19.0,8.0,15.0
351,671,Wood County,North Baltimore,3546,10,0,2,0,8,664.0,Wood County,3568.0,9.0,0.0,2.0,2.0,5.0
352,672,Wood County,Perrysburg,21732,7,0,3,4,0,665.0,Wood County,21548.0,8.0,0.0,3.0,3.0,2.0
353,674,Wood County,Bradner,1024,1,0,0,0,1,667.0,Wood County,1026.0,0.0,0.0,0.0,0.0,0.0
354,675,Wood County,Northwood,5423,19,0,2,4,13,669.0,Wood County,5376.0,6.0,0.0,2.0,3.0,1.0
355,676,Wood County,Pemberville,1425,0,0,0,0,0,670.0,Wood County,1433.0,1.0,0.0,1.0,0.0,0.0
356,677,Wood County,Wayne,927,0,0,0,0,0,671.0,Wood County,900.0,0.0,0.0,0.0,0.0,0.0

In [4]:
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_x":"2017 Population",
                                                              "VIOLENT CRIME_x":"2017 Violent Crime",
                                                              "MURDER_x":"2017 Murder", "RAPE_x": "2017 Rape",
                                                              "ROBBERY_x": "2017 Robbery", "AGGRAVATED ASSAULT_x": 
                                                              "2017 Aggravated Assault"})

# Rename our _y columns to 2016
combined_crime_df = combined_crime_df.rename(columns={"POPULATION_y":"2016 Population",
                                                              "VIOLENT CRIME_y":"2016 Violent Crime",
                                                              "MURDER_y":"2016 Murder", "RAPE_y": "2016 Rape",
                                                              "ROBBERY_y": "2016 Robbery", "AGGRAVATED ASSAULT_y": 
                                                              "2016 Aggravated Assault"})
combined_crime_df.head()

,Unnamed: 0_x,County_x,City,2017 Population,2017 Violent Crime,2017 Murder,2017 Rape,2017 Robbery,2017 Aggravated Assault,Unnamed: 0_y,County_y,2016 Population,2016 Violent Crime,2016 Murder,2016 Rape,2016 Robbery,2016 Aggravated Assault
0,7,Allen County,Lima,37220,275,5,52,81,137,9.0,Allen County,37715.0,356.0,8.0,44.0,123.0,181.0
1,8,Allen County,Bluffton,3987,1,0,1,0,0,10.0,Allen County,3953.0,1.0,0.0,0.0,1.0,0.0
2,9,Allen County,Delphos,3927,3,0,3,0,0,11.0,Allen County,3884.0,2.0,0.0,1.0,0.0,1.0
3,10,Allen County,Spencerville,2184,0,0,0,0,0,12.0,Allen County,2195.0,1.0,0.0,0.0,0.0,1.0
4,11,Allen County,Elida,1836,1,0,0,0,1,13.0,Allen County,1852.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# Merge our newly combined dataframe with the 2015 dataframe

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2015_df, how = 'outer', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2015 Population",
                                                        "VIOLENT CRIME":"2015 Violent Crime",
                                                        "MURDER":"2015 Murder", "RAPE": "2015 Rape",
                                                        "ROBBERY": "2015 Robbery", "AGGRAVATED ASSAULT": 
                                                        "2015 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2014_df, how = 'outer', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2014 Population",
                                                      "VIOLENT CRIME":"2014 Violent Crime",
                                                      "MURDER":"2014 Murder", "RAPE": "2014 Rape",
                                                      "ROBBERY": "2014 Robbery", "AGGRAVATED ASSAULT": 
                                                    "2014 Aggravated Assault"})

combined_crime_df = pd.merge(combined_crime_df, OHcrime_2013_df, how = 'outer', on="City")
combined_crime_df
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2013 Population",
                                                       "VIOLENT CRIME":"2013 Violent Crime",
                                                       "MURDER":"2013 Murder", "RAPE": "2013 Rape",
                                                       "ROBBERY": "2013 Robbery", "AGGRAVATED ASSAULT": 
                                                     "2013 Aggravated Assault"})
combined_crime_df = pd.merge(combined_crime_df, OHcrime_2012_df, how = 'outer', on="City")
combined_crime_df = combined_crime_df.rename(columns={"POPULATION":"2012 Population",
                                                       "VIOLENT CRIME":"2012 Violent Crime",
                                                       "MURDER":"2012 Murder", "RAPE": "2012 Rape",
                                                       "ROBBERY": "2012 Robbery", "AGGRAVATED ASSAULT": 
                                                     "2012 Aggravated Assault"})

combined_crimeGrouped = combined_crime_df.groupby("City")
combined_crime_df= combined_crimeGrouped.sum()
combined_crime_df=combined_crime_df.reset_index()
combined_crime_df.to_csv("Resources/CrimeData_merged.csv")
combined_crime_df.columns

Index(['City', 'Unnamed: 0_x', '2017 Population', '2017 Violent Crime',
       '2017 Murder', '2017 Rape', '2017 Robbery', '2017 Aggravated Assault',
       'Unnamed: 0_y', '2016 Population',
       ...
       '2013 Rape', '2013 Robbery', '2013 Aggravated Assault', 'Unnamed: 0',
       '2012 Population', '2012 Violent Crime', '2012 Murder', 'FORCIBLE RAPE',
       '2012 Robbery', 'AGG ASSAULT'],
      dtype='object', length=176)

In [6]:
Final_CrimeRateData = combined_crime_df[['City','2017 Population', '2017 Violent Crime',
         '2016 Population', '2016 Violent Crime', '2015 Population', '2015 Violent Crime', '2014 Population', '2014 Violent Crime']]

# violent_crimetableGrouped = violent_crimetable.groupby("City")
# Final_CrimeRateData= violent_crimetableGrouped.sum()
Final_CrimeRateData.head(20)
#new_df = pd.DataFrame(violent_crimetableGrouped["2017 Population", "2017 Violent Crime", "2016 Population", "2016 Violent
                      #Crime"].sum()
#DataFrame without City duplicates:

,City,2017 Population,2017 Violent Crime,2016 Population,2016 Violent Crime,2015 Population,2015 Violent Crime,2014 Population,2014 Violent Crime
0,Akron,197412.0,1377.0,197257.0,1216.0,197587.0,1225.0,197891.0,1366.0
1,Albany,899.0,0.0,918.0,0.0,909.0,0.0,889.0,1.0
2,Alliance,21838.0,75.0,43946.0,198.0,43968.0,262.0,44304.0,150.0
3,Amelia,4982.0,3.0,4957.0,0.0,4948.0,5.0,4919.0,3.0
4,Amherst,12090.0,5.0,12156.0,7.0,12171.0,5.0,12133.0,3.0
5,Apple Creek,1188.0,2.0,1186.0,0.0,1182.0,0.0,1181.0,0.0
6,Arcanum,0.0,0.0,0.0,0.0,0.0,0.0,2094.0,0.0
7,Archbold,4338.0,2.0,4342.0,4.0,4345.0,3.0,0.0,0.0
8,Ashland,20485.0,25.0,20278.0,24.0,20144.0,20.0,20293.0,15.0
9,Ashtabula,49924.0,42.0,49784.0,54.0,50154.0,59.0,50631.0,37.0
10,Ashville,4211.0,3.0,4207.0,1.0,4160.0,3.0,4113.0,2.0
11,Athens,25526.0,34.0,25203.0,27.0,23960.0,22.0,24083.0,27.0
12,Aurora,15932.0,3.0,15897.0,11.0,15783.0,6.0,15586.0,9.0
13,Austintown,35303.0,62.0,35680.0,52.0,0.0,0.0,35997.0,64.0
14,Avon Lake,23839.0,8.0,23625.0,1.0,0.0,0.0,0.0,0.0
15,Baltimore,2973.0,0.0,2970.0,1.0,2961.0,2.0,2952.0,0.0
16,Barberton,26050.0,103.0,26172.0,75.0,26242.0,58.0,26286.0,68.0
17,Barnesville,4096.0,0.0,4112.0,1.0,4127.0,5.0,4129.0,0.0
18,Batavia,1656.0,0.0,1654.0,6.0,1652.0,2.0,1644.0,2.0
19,Bay Village,15327.0,2.0,15346.0,2.0,15387.0,7.0,15435.0,3.0

In [7]:

Final_CrimeRateData["Crime Rate 2017"] = ((Final_CrimeRateData["2017 Violent Crime"])/(Final_CrimeRateData["2017 Population"]))*100
Final_CrimeRateData["Crime Rate 2016"] = ((Final_CrimeRateData["2016 Violent Crime"])/(Final_CrimeRateData["2016 Population"]))*100
Final_CrimeRateData["Crime Rate 2015"] = ((Final_CrimeRateData["2015 Violent Crime"])/(Final_CrimeRateData["2015 Population"]))*100
Final_CrimeRateData["Crime Rate 2014"] = ((Final_CrimeRateData["2014 Violent Crime"])/(Final_CrimeRateData["2014 Population"]))*100

Final_CrimeRateData.head()
# #violent_crimetableUpdate = violent_crimetable.sort_values("2017 Population", ascending=False)
Final_CrimeRateData.to_csv("Resources/CrimeRate.csv")
Final_CrimeRateData.head()

C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\maria\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,City,2017 Population,2017 Violent Crime,2016 Population,2016 Violent Crime,2015 Population,2015 Violent Crime,2014 Population,2014 Violent Crime,Crime Rate 2017,Crime Rate 2016,Crime Rate 2015,Crime Rate 2014
0,Akron,197412.0,1377.0,197257.0,1216.0,197587.0,1225.0,197891.0,1366.0,0.697526,0.616455,0.619980,0.690279
1,Albany,899.0,0.0,918.0,0.0,909.0,0.0,889.0,1.0,0.000000,0.000000,0.000000,0.112486
2,Alliance,21838.0,75.0,43946.0,198.0,43968.0,262.0,44304.0,150.0,0.343438,0.450553,0.595888,0.338570
3,Amelia,4982.0,3.0,4957.0,0.0,4948.0,5.0,4919.0,3.0,0.060217,0.000000,0.101051,0.060988
4,Amherst,12090.0,5.0,12156.0,7.0,12171.0,5.0,12133.0,3.0,0.041356,0.057585,0.041081,0.024726